### ISSUE TITLE
Git repo name doesn't match Cabal package name

### ISSUE THREAD

**Issue by ericpashman** [dimitri-xyz/coinbase-pro-exchange#15]
The project's `.cabal` config should probably be updated to match the the new Git repo name. As is, it's a bit confusing, e.g., if you have to specify a build target. I found myself staring at the screen wondering what the error was after typing

    stack ghci coinbase-pro-exchange:test-coinbase

before I realized the package name hadn't been updated. We should also consider renaming the existing build targets (e.g., `test-coinbase`) to be more obvious and consistent (`test-coinbase-pro-exhange` is at least consistent, but why not just `test`?)

And while we're here, I'll mention that I think the repo name is a bit odd, with the "exchange" part seemingly there only because for some reason the project formerly got renamed from `gdax` to `coinbase-exchange` rather than to `coinbase-pro`. I think calling it something like `haskell-coinbase-pro` makes the most sense. That said, renaming the repo means everybody using it has to update remotes in `git`, so if we do want to change the name, it'll be least disruptive to do it as soon as possible.

**Comment by dimitri-xyz** [comment]
I believe the word "exchange" is just a historical artifact at this point. In the beginning, when Coinbase did not have an exchange, it already had an API for its wallet. Now, we are just stuck with this word.

Let's change the name of the repo to: "haskell-coinbase-pro" as you suggested. It makes it very clear what the code is about.

**Comment by dimitri-xyz** [comment]
I already changed the repo name. That's painful and should be done early. changes in the files can follow now.

**Comment by ericpashman** [comment]
OK, I'll make the necessary changes in the package config files and README shortly.

FYI, for anybody who might be out there following along, to update to the repo's new URL, use `git remote set-url`. If you've cloned the repo in the usual way, run:

    git remote set-url origin https://github.com/dimitri-xyz/haskell-coinbase-pro.git

Edit: Whoops, fixed remote name in the above command.

**Comment by dimitri-xyz** [comment]
Thanks for fixing this!
